<?php

return [
    [
        'name' => 'theme',
        'title' => '皮肤',
        'type' => 'string',
        'content' => [],
        'value' => 'default',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'menu',
        'title' => '顶部菜单',
        'type' => 'text',
        'content' => [],
        'value' => '主站|/',
        'rule' => 'required',
        'msg' => '',
        'tip' => '一行代表一条链接(回车换行)<br>格式为:展示文字|链接地址<br> 如:主站|/',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'title',
        'title' => '右侧标题',
        'type' => 'text',
        'content' => [],
        'value' => 'bbs论坛',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'brief',
        'title' => '论坛介绍',
        'type' => 'text',
        'content' => [],
        'value' => 'FastAdmin是一款基于ThinkPHP5+Bootstrap的极速后台开发框架。这是一个FastAdmin的论坛插件',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'url',
        'title' => '友情链接',
        'type' => 'text',
        'content' => [],
        'value' => 'FastAdmin|https://www.fastadmin.net'."\r\n"
            .'FastAdmin社区|https://ask.fastadmin.net/',
        'rule' => 'required',
        'msg' => '',
        'tip' => '一行代表一条链接(回车换行)<br>格式为:链接展示文字|链接地址<br> 如:百度|https://www.baidu.com',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'rewrite',
        'title' => '伪静态',
        'type' => 'array',
        'content' => [],
        'value' => [
            'index/index' => '/b/$',
            'thread/info' => '/b/t/$',
            'thread/add' => 'b/t/c',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
